In [ ]:
import pandas as pd
import tensorflow as tf
import numpy as np

In [ ]:
!gdown "11yzwVaWumFEqVUDsd_lDl7tYn0WewYeF&confirm=t"

Downloading...
From: https://drive.google.com/uc?id=11yzwVaWumFEqVUDsd_lDl7tYn0WewYeF&confirm=t
To: /content/Laifu_Food.csv
100% 36.3k/36.3k [00:00<00:00, 49.5MB/s]


In [ ]:
url = '/content/Laifu_Food.csv'
df = pd.read_csv(url)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 267 entries, 0 to 266
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Food ID                  267 non-null    int64  
 1   Food Name                267 non-null    object 
 2   Cuisine                  267 non-null    object 
 3   Ingredients              267 non-null    object 
 4   Spice Level              267 non-null    object 
 5   Rating                   267 non-null    float64
 6   Recommended For          267 non-null    object 
 7   Physical Activity Level  267 non-null    object 
 8   Stress Level             267 non-null    object 
 9   BMI Category             267 non-null    object 
 10  Blood Pressure           267 non-null    object 
 11  Preference               267 non-null    object 
dtypes: float64(1), int64(1), object(10)
memory usage: 25.2+ KB


In [ ]:
df.head(10)

Food ID    Food Name     Cuisine  \
0        1  Nasi Goreng  Indonesian   
1        2      Rendang  Indonesian   
2        3    Gado-Gado  Indonesian   
3        4  Nasi Padang  Indonesian   
4        5    Soto Ayam  Indonesian   
5        6     Martabak  Indonesian   
6        7        Bakso  Indonesian   
7        8    Sate Ayam  Indonesian   
8        9    Nasi Uduk  Indonesian   
9       10       Pempek  Indonesian   

                                         Ingredients Spice Level  Rating  \
0  Fried rice, chicken, prawns, eggs, shallots, s...    Moderate     4.5   
1  Spicy beef stew, coconut milk, lemongrass, gal...        High     4.8   
2  Mixed vegetable salad, peanut sauce, tofu, tempeh        Mild     4.7   
3  Steamed rice, rendang, sambal, curried fish, c...        High     4.6   
4  Chicken soup, vermicelli, shredded chicken, tu...        Mild     4.7   
5    Stuffed pancake with chocolate, cheese, peanuts        Mild     4.9   
6           Meatball soup, noodles, tofu, vegetables        Mild     4.8   
7  Grilled chicken skewers, peanut sauce, sweet s...    Moderate     4.6   
8  Coconut rice, fried chicken, anchovies, peanut...        Mild     4.7   
9                   Fishcake, tapioca, vinegar sauce        Mild     4.5   

            Recommended For Physical Activity Level Stress Level BMI Category  \
0          Street Food Fans                    High         Mild       Normal   
1    Spicy Food Enthusiasts                    High     Moderate   Overweight   
2               Vegetarians                    High          Low       Normal   
3    Spicy Food Enthusiasts                    High         Mild       Normal   
4               Soup Lovers                    High     Moderate       Normal   
5         Street Snack Fans                     Low          Low       Normal   
6               Soup Lovers                    High         High   Overweight   
7               Meat Lovers                    High     Moderate       Normal   
8  Comfort Food Enthusiasts                    High     Moderate   Overweight   
9          Street Food Fans                    High         High   Overweight   

  Blood Pressure  Preference  
0         120/80      Savory  
1         130/85      Savory  
2         118/75  Vegetarian  
3         120/80      Savory  
4         120/80     Neutral  
5         118/75       Sweet  
6         130/85      Savory  
7         120/80      Savory  
8         130/85      Savory  
9         130/85      Savory

In [ ]:
output = df[['Food Name', 'Ingredients']]

# Drop duplicates based on 'Food Name'
output = output.drop_duplicates(subset='Food Name')

# Add a new 'Index' column with sequential indices
output['Index'] = range(len(output))

output

Food Name                                        Ingredients  \
0         Nasi Goreng  Fried rice, chicken, prawns, eggs, shallots, s...   
1             Rendang  Spicy beef stew, coconut milk, lemongrass, gal...   
2           Gado-Gado  Mixed vegetable salad, peanut sauce, tofu, tempeh   
3         Nasi Padang  Steamed rice, rendang, sambal, curried fish, c...   
4           Soto Ayam  Chicken soup, vermicelli, shredded chicken, tu...   
5            Martabak    Stuffed pancake with chocolate, cheese, peanuts   
6               Bakso           Meatball soup, noodles, tofu, vegetables   
7           Sate Ayam  Grilled chicken skewers, peanut sauce, sweet s...   
8           Nasi Uduk  Coconut rice, fried chicken, anchovies, peanut...   
9              Pempek                   Fishcake, tapioca, vinegar sauce   
10        Ayam Penyet  Smashed fried chicken, sambal, cucumber, tempe...   
11         Sop Buntut           Oxtail soup, carrots, potatoes, tomatoes   
12      Pisang Goreng                                 Deep-fried bananas   
13       Sambal Matah                  Raw shallot and lemongrass sambal   
14       Sate Kambing  Grilled lamb skewers, sweet soy sauce, peanut ...   
15         Pecel Lele            Fried catfish, peanut sauce, vegetables   
16           Ketoprak  Tofu, rice cake, vermicelli, peanut sauce, cra...   
17         Ikan Bakar                     Grilled fish with sambal, lime   
18        Soto Betawi  Beef soup, coconut milk, tomatoes, potatoes, v...   
19         Bubur Ayam  Chicken porridge, shredded chicken, fried shal...   
20         Rujak Buah     Fruit salad, tamarind dressing, peanuts, chili   
21      Lontong Sayur     Rice cake soup, tofu, vegetables, coconut milk   
22             Serabi                   Coconut pancakes with palm sugar   
23        Sate Padang  Grilled beef skewers with Padang-style spicy s...   
24         Pisang Ijo  Banana wrapped in green pancake, palm sugar, c...   
25             Asinan      Preserved fruits and vegetables, peanut sauce   
26         Mie Goreng  Fried noodles, chicken, prawns, vegetables, sw...   
27     Rendang Burger          Beef rendang in a burger with sambal mayo   
28           Es Teler  Mixed fruit cocktail with avocado, coconut, co...   
29        Soto Madura  Chicken soup with shredded chicken, vermicelli...   
30      Gulai Kambing   Lamb curry with coconut milk, turmeric, galangal   
31        Nasi Kuning  Yellow rice with fried chicken, anchovies, pea...   
32         Sate Lilit  Minced fish or meat satay wrapped around bambo...   
33        Sayur Lodeh       Vegetable stew in coconut milk, tofu, tempeh   
34           Tahu Tek  Fried tofu with peanut sauce, boiled eggs, ric...   
35   Pempek Palembang               Fishcake, spongy cake, vinegar sauce   
36      Coto Makassar                 Beef soup with nuts, herbs, spices   
37       Laksa Betawi  Spicy noodle soup with coconut milk, chicken, ...   
38        Bubur Ketan  Sticky rice porridge with chicken, mushrooms, ...   
39         Sate Kulit  Grilled skewers made from cow skin, sweet soy ...   
40         Nasi Liwet   Rice cooked in coconut milk, chicken, vegetables   
41         Lodeh Jawa       Vegetable stew in coconut milk, tofu, tempeh   
42      Bakwan Malang   Meatballs, tofu, fried shrimp, vegetables, broth   
43       Sambal Udang                      Spicy shrimp with chili sauce   
44       Nasi Tumpeng           Conical yellow rice, various side dishes   
45     Asinan Jakarta      Preserved fruits and vegetables, peanut sauce   
46              Rawon             Black beef soup, keluak, herbs, spices   
47        Nasi Campur                Mixed rice with various side dishes   
48       Rujak Cingur  Salad with beef snout, fruits, vegetables, shr...   
49            Sop Iga       Beef rib soup with vegetables, herbs, spices   
50       Bebek Goreng                  Fried duck, sweet soy sauce, lime   
51       Pisang Molen                             Deep-fried

In [ ]:
#Drop Food ID, Rating, Cuisine Column and Empty Column
df.drop(columns=['Food ID','Rating','Cuisine'], inplace=True)
df.dropna(inplace=True)

#Replace BMI Category into List of Number
df['BMI Category'].replace({'Underweight':0,'Normal':0,'Normal Weight':0,'Overweight':1,'Obese':2},inplace=True)

#Replace Spice Level into List of Number
unique_spice = df['Spice Level'].unique()
df['Spice Level'].replace(to_replace=unique_spice, value=list(range(len(unique_spice))), inplace=True)

#Replace Physical Activity Level into List of Number
unique_physical = df['Physical Activity Level'].unique()
df['Physical Activity Level'].replace(to_replace=unique_physical, value=list(range(len(unique_physical))), inplace=True)

#Replace Stress Level into List of Number
unique_stress = df['Stress Level'].unique()
df['Stress Level'].replace(to_replace=unique_stress, value=list(range(len(unique_stress))), inplace=True)

#Replace Preference into List of Number
unique_preference = df['Preference'].unique()
df['Preference'].replace(to_replace=unique_preference, value=list(range(len(unique_preference))), inplace=True)

#Replace Recommended For into List of Number
unique_reccomended = df['Recommended For'].unique()
df['Recommended For'].replace(to_replace=unique_reccomended, value=list(range(len(unique_reccomended))), inplace=True)

#Replace Food Name into List of Number
unique_food = df['Food Name'].unique()
df['Food Name'].replace(to_replace=unique_food, value=list(range(len(unique_food))), inplace=True)

#Split Blood Pressure Column into Sistole and Diastole
df[['Sistole', 'Diastole']] = df['Blood Pressure'].str.split('/', expand=True)
df.drop(columns=['Blood Pressure'], inplace=True)

df[['Sistole', 'Diastole', 'Recommended For', 'Preference']] = df[['Sistole', 'Diastole', 'Recommended For', 'Preference']].astype(np.int64)

In [ ]:
unique_spice

array(['Moderate', 'High', 'Mild'], dtype=object)

In [ ]:
unique_reccomended

array(['Street Food Fans', 'Spicy Food Enthusiasts', 'Vegetarians',
       'Soup Lovers', 'Street Snack Fans', 'Meat Lovers',
       'Comfort Food Enthusiasts', 'Seafood Enthusiasts',
       'Healthy Eaters', 'Indonesian Dessert Lovers',
       'Food Fusion Enthusiasts', 'Celebrations', 'Seafood Lovers',
       'Adventurous Eaters'], dtype=object)

In [ ]:
unique_physical

array(['High', 'Low', 'Moderate'], dtype=object)

In [ ]:
unique_stress

array(['Mild', 'Moderate', 'Low', 'High'], dtype=object)

In [ ]:
unique_preference

array(['Savory', 'Vegetarian', 'Neutral', 'Sweet', 'Spicy'], dtype=object)

In [ ]:
df.info()
df.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 267 entries, 0 to 266
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Food Name                267 non-null    int64 
 1   Ingredients              267 non-null    object
 2   Spice Level              267 non-null    int64 
 3   Recommended For          267 non-null    int64 
 4   Physical Activity Level  267 non-null    int64 
 5   Stress Level             267 non-null    int64 
 6   BMI Category             267 non-null    int64 
 7   Preference               267 non-null    int64 
 8   Sistole                  267 non-null    int64 
 9   Diastole                 267 non-null    int64 
dtypes: int64(9), object(1)
memory usage: 21.0+ KB


Food Name                                        Ingredients  Spice Level  \
0          0  Fried rice, chicken, prawns, eggs, shallots, s...            0   
1          1  Spicy beef stew, coconut milk, lemongrass, gal...            1   
2          2  Mixed vegetable salad, peanut sauce, tofu, tempeh            2   
3          3  Steamed rice, rendang, sambal, curried fish, c...            1   
4          4  Chicken soup, vermicelli, shredded chicken, tu...            2   
5          5    Stuffed pancake with chocolate, cheese, peanuts            2   
6          6           Meatball soup, noodles, tofu, vegetables            2   
7          7  Grilled chicken skewers, peanut sauce, sweet s...            0   
8          8  Coconut rice, fried chicken, anchovies, peanut...            2   
9          9                   Fishcake, tapioca, vinegar sauce            2   

   Recommended For  Physical Activity Level  Stress Level  BMI Category  \
0                0                        0             0             0   
1                1                        0             1             1   
2                2                        0             2             0   
3                1                        0             0             0   
4                3                        0             1             0   
5                4                        1             2             0   
6                3                        0             3             1   
7                5                        0             1             0   
8                6                        0             1             1   
9                0                        0             3             1   

   Preference  Sistole  Diastole  
0           0      120        80  
1           0      130        85  
2           1      118        75  
3           0      120        80  
4           2      120        80  
5           3      118        75  
6           0      130        85  
7           0      120        80  
8           0      130        85  
9           0      130        85

In [ ]:
x = df.drop(columns=['Food Name', 'Ingredients'])
y = df['Food Name']

In [ ]:
x.dtypes

Spice Level                int64
Recommended For            int64
Physical Activity Level    int64
Stress Level               int64
BMI Category               int64
Preference                 int64
Sistole                    int64
Diastole                   int64
dtype: object

In [ ]:
train_size = int(0.7 * x.shape[0])

x_train = x[:train_size]
y_train = y[:train_size]

x_valid = x[train_size:]
y_valid = y[train_size:]

In [ ]:
tf_dataset = tf.data.Dataset.from_tensor_slices((x_train.values, y_train.values)).batch(32)
tf_dataset_val = tf.data.Dataset.from_tensor_slices((x_valid.values, y_valid.values)).batch(32)

In [ ]:
for features, targets in tf_dataset.take(1):
  print ('Features: {}, Target: {}'.format(features, targets))

Features: [[  0   0   0   0   0   0 120  80]
 [  1   1   0   1   1   0 130  85]
 [  2   2   0   2   0   1 118  75]
 [  1   1   0   0   0   0 120  80]
 [  2   3   0   1   0   2 120  80]
 [  2   4   1   2   0   3 118  75]
 [  2   3   0   3   1   0 130  85]
 [  0   5   0   1   0   0 120  80]
 [  2   6   0   1   1   0 130  85]
 [  2   0   0   3   1   0 130  85]
 [  1   1   0   0   1   0 130  85]
 [  2   3   0   1   1   0 130  85]
 [  2   4   1   2   0   3 118  75]
 [  1   1   0   2   0   4 122  78]
 [  0   5   0   0   1   0 130  85]
 [  2   7   0   3   1   0 130  85]
 [  2   2   0   0   0   0 120  80]
 [  1   7   0   2   0   0 118  75]
 [  2   3   0   0   0   2 120  80]
 [  2   6   0   3   1   2 130  85]
 [  2   8   0   2   0   4 118  75]
 [  2   2   0   0   1   0 130  85]
 [  2   9   1   1   0   3 120  80]
 [  1   5   0   2   0   4 122  78]
 [  2   9   1   2   0   3 118  75]
 [  2   8   0   3   1   0 130  85]
 [  0   0   0   0   0   0 120  80]
 [  0  10   2   1   1   0 130  85]
 [  2   9 

In [ ]:
from keras.callbacks import ModelCheckpoint

model = tf.keras.models.Sequential([
    tf.keras.layers.Embedding(1000, 1024, input_length=8),
    tf.keras.layers.Conv1D(128, 5, activation='relu'),
    # tf.keras.layers.LSTM(256, return_sequences=True),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.GlobalAveragePooling1D(),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(54, activation='sigmoid')
])

model.summary()

checkpoint = ModelCheckpoint(filepath = './checkpoint//model.{epoch:02d}-{val_accuracy:06f}.h5', monitor = 'val_accuracy', save_best_only = True)

model.compile(loss='sparse_categorical_crossentropy',
                  optimizer = tf.keras.optimizers.Adam(learning_rate = 0.0005),
                  metrics=['accuracy'])

model.fit(tf_dataset, epochs = 100,  validation_data = tf_dataset_val, callbacks = [checkpoint])

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 1024)           1024000   
                                                                 
 conv1d (Conv1D)             (None, 4, 128)            655488    
                                                                 
 batch_normalization (Batch  (None, 4, 128)            512       
 Normalization)                                                  
                                                                 
 global_average_pooling1d (  (None, 128)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 256)               33024     
                                                                 
 dropout (Dropout)           (None, 256)               0

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


6/6 [==============================] - 6s 489ms/step - loss: 3.6075 - accuracy: 0.2473 - val_loss: 3.9503 - val_accuracy: 0.1605
Epoch 2/100
6/6 [==============================] - 1s 190ms/step - loss: 2.8197 - accuracy: 0.6129 - val_loss: 3.9034 - val_accuracy: 0.3457
Epoch 3/100
6/6 [==============================] - 1s 213ms/step - loss: 2.3208 - accuracy: 0.6667 - val_loss: 3.8517 - val_accuracy: 0.4198
Epoch 4/100
6/6 [==============================] - 1s 236ms/step - loss: 1.8677 - accuracy: 0.7204 - val_loss: 3.7982 - val_accuracy: 0.5309
Epoch 5/100
6/6 [==============================] - 1s 225ms/step - loss: 1.5937 - accuracy: 0.6882 - val_loss: 3.7421 - val_accuracy: 0.5309
Epoch 6/100
6/6 [==============================] - 1s 185ms/step - loss: 1.2673 - accuracy: 0.7849 - val_loss: 3.6858 - val_accuracy: 0.5926
Epoch 7/100
6/6 [==============================] - 1s 242ms/step - loss: 1.0565 - accuracy: 0.8441 - val_loss: 3.6285 - val_accuracy: 0.6790
Epoch 8/100
6/6 [========

In [ ]:
import numpy as np
new_x = np.array([1, 1, 0, 1, 1, 0, 140, 90])
new_x = {'Spice Level': new_x[0], 'Recommended For': new_x[1], 'Physical Activity Level': new_x[2], 'Stress Level': new_x[3],
         'BMI Category': new_x[4], 'Preference': new_x[5], 'Sistole': new_x[6], 'Diastole': new_x[7]}
new_x = pd.DataFrame(data=new_x, index=[0])
new_x

Spice Level  Recommended For  Physical Activity Level  Stress Level  \
0            1                1                        0             1   

   BMI Category  Preference  Sistole  Diastole  
0             1           0      140        90

In [ ]:
new_x = tf.convert_to_tensor(new_x)
new_x

<tf.Tensor: shape=(1, 8), dtype=int64, numpy=array([[  1,   1,   0,   1,   1,   0, 140,  90]])>

In [ ]:
result = model.predict(new_x)
result

1/1 [==============================] - 0s 114ms/step


array([[3.97552249e-05, 9.99809146e-01, 1.03052684e-04, 4.53348815e-01,
        1.45531986e-02, 3.27978982e-04, 1.13418910e-05, 1.44146295e-04,
        2.53161073e-01, 1.21900257e-05, 8.75029683e-01, 7.20085736e-05,
        7.04793492e-04, 2.22287446e-01, 3.12609154e-05, 2.33583312e-04,
        6.87792908e-06, 2.56977801e-04, 3.89794513e-06, 8.94962614e-06,
        5.96406928e-04, 1.11440138e-04, 9.86880124e-01, 1.02894555e-05,
        2.69611087e-03, 4.15265495e-05, 7.80863866e-06, 3.66822690e-01,
        2.90933185e-05, 4.06656036e-05, 1.03778005e-01, 5.89574222e-04,
        1.35407536e-05, 4.70617624e-06, 2.27232218e-01, 8.69151700e-06,
        8.52589846e-01, 1.98363536e-03, 9.85224833e-05, 1.00304089e-04,
        2.07213275e-02, 2.00473050e-06, 1.48844574e-05, 8.73132831e-06,
        3.44844477e-04, 2.06859804e-05, 4.97343153e-01, 3.16795467e-06,
        1.48818117e-06, 7.07716245e-05, 8.29846323e-01, 8.06333404e-03,
        1.05520294e-05, 9.13456315e-05]], dtype=float32)

In [ ]:
max_index = np.argmax(result)
selected_row = output.loc[max_index]
print('Food recommendation:', selected_row['Food Name'])
print('Ingredients:',selected_row['Ingredients'])

Food recommendation: Rendang
Ingredients: Spicy beef stew, coconut milk, lemongrass, galangal


In [ ]:
import tensorflow as tf

model = tf.keras.models.load_model('/content/checkpoint/model.92-0.876543.h5')
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open("Laifu_FoodRecommendation.tflite", "wb").write(tflite_model)

6911504