# Module Import and Read Data

In [ ]:
import pandas as pd
import tensorflow as tf
import numpy as np

In [ ]:
!gdown "1CATQA0nJHOt-XKRQA3vTBvWK1W3QeMKm&confirm=t"

Downloading...
From: https://drive.google.com/uc?id=1CATQA0nJHOt-XKRQA3vTBvWK1W3QeMKm&confirm=t
To: /content/Laifu_Sleep.csv
100% 22.8k/22.8k [00:00<00:00, 8.35MB/s]


In [ ]:
url = '/content/Laifu_Sleep.csv'
df = pd.read_csv(url)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 378 entries, 0 to 377
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Person ID                378 non-null    int64  
 1   Gender                   378 non-null    object 
 2   Age                      378 non-null    int64  
 3   Occupation               378 non-null    object 
 4   Sleep Duration           378 non-null    float64
 5   Physical Activity Level  377 non-null    float64
 6   Stress Level             378 non-null    int64  
 7   BMI Category             378 non-null    object 
 8   Blood Pressure           377 non-null    object 
 9   Heart Rate               378 non-null    int64  
 10  Daily Steps              376 non-null    float64
 11  Sleep Quality            378 non-null    float64
dtypes: float64(4), int64(4), object(4)
memory usage: 35.6+ KB


In [ ]:
df.head(10)

Person ID Gender  Age            Occupation  Sleep Duration  \
0          1   Male   27     Software Engineer             6.1   
1          2   Male   28                Doctor             6.2   
2          3   Male   28                Doctor             6.2   
3          4   Male   28  Sales Representative             5.9   
4          5   Male   28  Sales Representative             5.9   
5          6   Male   28     Software Engineer             5.9   
6          7   Male   29               Teacher             6.3   
7          8   Male   29                Doctor             7.8   
8          9   Male   29                Doctor             7.8   
9         10   Male   29                Doctor             7.8   

   Physical Activity Level  Stress Level BMI Category Blood Pressure  \
0                     42.0             6   Overweight         126/83   
1                     60.0             8       Normal         125/80   
2                     60.0             8       Normal         125/80   
3                     30.0             8        Obese         140/90   
4                     30.0             8        Obese         140/90   
5                     30.0             8        Obese         140/90   
6                     40.0             7        Obese         140/90   
7                     75.0             6       Normal         120/80   
8                     75.0             6       Normal         120/80   
9                     75.0             6       Normal         120/80   

   Heart Rate  Daily Steps  Sleep Quality  
0          77       4200.0          55.05  
1          75      10000.0          68.25  
2          75      10000.0          68.25  
3          85       3000.0          47.25  
4          85       3000.0          47.25  
5          85       3000.0          42.25  
6          82       3500.0          51.90  
7          70       8000.0          78.00  
8          70       8000.0          78.00  
9          70       8000.0          78.00

# Data Preprocessing

In [ ]:
#Drop Person ID Column and Empty Column
df.drop(columns=['Person ID'], inplace=True)
df.dropna(inplace=True)

In [ ]:
#Replace Gender into Female and Male
df['Gender'].replace({'Female':0,'Male':1},inplace=True)

#Replace BMI Category into List of Number
df['BMI Category'].replace({'Normal':0,'Normal Weight':0,'Overweight':1,'Obese':2},inplace=True)

#Replace Occupation into List of Number
unique_occupation = df['Occupation'].unique()
df['Occupation'].replace(to_replace=unique_occupation, value=list(range(len(unique_occupation))), inplace=True)

#Split Blood Pressure Column into Sistole and Diastole
df[['Sistole', 'Diastole']] = df['Blood Pressure'].str.split('/', expand=True)
df[['Sistole', 'Diastole', 'Daily Steps', 'Physical Activity Level']] = df[['Sistole', 'Diastole', 'Daily Steps', 'Physical Activity Level']].astype(np.int64)
df.drop(columns=['Blood Pressure'], inplace=True)

In [ ]:
x = df.drop(columns=['Sleep Quality'])
y = df['Sleep Quality']

In [ ]:
x.dtypes

Gender                       int64
Age                          int64
Occupation                   int64
Sleep Duration             float64
Physical Activity Level      int64
Stress Level                 int64
BMI Category                 int64
Heart Rate                   int64
Daily Steps                  int64
Sistole                      int64
Diastole                     int64
dtype: object

In [ ]:
#y = y.astype(np.float64)

In [ ]:
#tf_dataset = tf.data.Dataset.from_tensor_slices((x.values, y.values))

In [ ]:
train_size = int(0.8 * x.shape[0])

x_train = x[:train_size]
y_train = y[:train_size]

x_valid = x[train_size:]
y_valid = y[train_size:]

In [ ]:
x_train.dtypes

Gender                       int64
Age                          int64
Occupation                   int64
Sleep Duration             float64
Physical Activity Level      int64
Stress Level                 int64
BMI Category                 int64
Heart Rate                   int64
Daily Steps                  int64
Sistole                      int64
Diastole                     int64
dtype: object

In [ ]:
x_train.head(10)

Gender  Age  Occupation  Sleep Duration  Physical Activity Level  \
0       1   27           0             6.1                       42   
1       1   28           1             6.2                       60   
2       1   28           1             6.2                       60   
3       1   28           2             5.9                       30   
4       1   28           2             5.9                       30   
5       1   28           0             5.9                       30   
6       1   29           3             6.3                       40   
7       1   29           1             7.8                       75   
8       1   29           1             7.8                       75   
9       1   29           1             7.8                       75   

   Stress Level  BMI Category  Heart Rate  Daily Steps  Sistole  Diastole  
0             6             1          77         4200      126        83  
1             8             0          75        10000      125        80  
2             8             0          75        10000      125        80  
3             8             2          85         3000      140        90  
4             8             2          85         3000      140        90  
5             8             2          85         3000      140        90  
6             7             2          82         3500      140        90  
7             6             0          70         8000      120        80  
8             6             0          70         8000      120        80  
9             6             0          70         8000      120        80

In [ ]:
tf_dataset = tf.data.Dataset.from_tensor_slices((x_train.values, y_train.values)).batch(32)
tf_dataset_val = tf.data.Dataset.from_tensor_slices((x_valid.values, y_valid.values)).batch(32)

In [ ]:
for features, targets in tf_dataset.take(1):
  print ('Features: {}, Target: {}'.format(features, targets))

Features: [[1.00e+00 2.70e+01 0.00e+00 6.10e+00 4.20e+01 6.00e+00 1.00e+00 7.70e+01
  4.20e+03 1.26e+02 8.30e+01]
 [1.00e+00 2.80e+01 1.00e+00 6.20e+00 6.00e+01 8.00e+00 0.00e+00 7.50e+01
  1.00e+04 1.25e+02 8.00e+01]
 [1.00e+00 2.80e+01 1.00e+00 6.20e+00 6.00e+01 8.00e+00 0.00e+00 7.50e+01
  1.00e+04 1.25e+02 8.00e+01]
 [1.00e+00 2.80e+01 2.00e+00 5.90e+00 3.00e+01 8.00e+00 2.00e+00 8.50e+01
  3.00e+03 1.40e+02 9.00e+01]
 [1.00e+00 2.80e+01 2.00e+00 5.90e+00 3.00e+01 8.00e+00 2.00e+00 8.50e+01
  3.00e+03 1.40e+02 9.00e+01]
 [1.00e+00 2.80e+01 0.00e+00 5.90e+00 3.00e+01 8.00e+00 2.00e+00 8.50e+01
  3.00e+03 1.40e+02 9.00e+01]
 [1.00e+00 2.90e+01 3.00e+00 6.30e+00 4.00e+01 7.00e+00 2.00e+00 8.20e+01
  3.50e+03 1.40e+02 9.00e+01]
 [1.00e+00 2.90e+01 1.00e+00 7.80e+00 7.50e+01 6.00e+00 0.00e+00 7.00e+01
  8.00e+03 1.20e+02 8.00e+01]
 [1.00e+00 2.90e+01 1.00e+00 7.80e+00 7.50e+01 6.00e+00 0.00e+00 7.00e+01
  8.00e+03 1.20e+02 8.00e+01]
 [1.00e+00 2.90e+01 1.00e+00 7.80e+00 7.50e+01 6.00e+0

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(32, activation = 'relu', input_shape = (11, )),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(8, activation='relu'),
    tf.keras.layers.Dense(1)
])

model.summary()

model.compile(optimizer = tf.keras.optimizers.Adam(), loss = 'mae', metrics = ['mae'])

model.fit(tf_dataset, epochs = 10, verbose = 1, validation_data = tf_dataset_val)

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_22 (Dense)            (None, 32)                384       
                                                                 
 dense_23 (Dense)            (None, 16)                528       
                                                                 
 dense_24 (Dense)            (None, 8)                 136       
                                                                 
 dense_25 (Dense)            (None, 1)                 9         
                                                                 
Total params: 1057 (4.13 KB)
Trainable params: 1057 (4.13 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/10
10/10 [==============================] - 1s 19ms/step - loss: 404.7098 - mae: 404.7098 - val_loss: 206.5381 - val_mae: 206.5381
Epoch 2/10
10/1

In [ ]:
import numpy as np
new_x = np.array([1, 59, 3, 7.2, 36, 5, 1, 65, 7000, 120, 80])
new_x = {'Gender': new_x[0], 'Age': new_x[1], 'Occupation': new_x[2], 'Sleep Duration': new_x[3], 'Physical Activity Level': new_x[4],
                      'Stress Level': new_x[5], 'BMI Category': new_x[6], 'Heart Rate': new_x[7], 'Daily Steps': new_x[8],
                      'Sistole': new_x[9], 'Diastole': new_x[10]}
new_x = pd.DataFrame(data=new_x, index=[0])
new_x

Gender   Age  Occupation  Sleep Duration  Physical Activity Level  \
0     1.0  59.0         3.0             7.2                     36.0   

   Stress Level  BMI Category  Heart Rate  Daily Steps  Sistole  Diastole  
0           5.0           1.0        65.0       7000.0    120.0      80.0

In [ ]:
new_x = tf.convert_to_tensor(new_x)
new_x

<tf.Tensor: shape=(1, 11), dtype=float64, numpy=
array([[1.0e+00, 5.9e+01, 3.0e+00, 7.2e+00, 3.6e+01, 5.0e+00, 1.0e+00,
        6.5e+01, 7.0e+03, 1.2e+02, 8.0e+01]])>

In [ ]:
model.predict(new_x)

1/1 [==============================] - 0s 53ms/step


array([[70.05366]], dtype=float32)